minimum_pre_commit_version: 2.9.2
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
    -   id: csslint
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.3
    hooks:
    -   id: jshint
